// <auto-generated />
using System;
using HealthAggregatorV2.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HealthDbContext))]
    [Migration("20260110224709_AddAdvancedOuraMetrics")]
    partial class AddAdvancedOuraMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthAggregatorV2.Domain.Entities.DailySummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActivityScore")
                        .HasColumnType("int");

                    b.Property<double?>("BodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<int?>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<int?>("CaloriesConsumed")
                        .HasColumnType("int");

                    b.Property<double?>("CarbsGrams")
                        .HasColumnType("float");

                    b.Property<int?>("CardiovascularAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DailyStress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DeepSleepDuration")
                        .HasColumnType("int");

                    b.Property<double?>("FatGrams")
                        .HasColumnType("float");

                    b.Property<int?>("HeartRateAvg")
                        .HasColumnType("int");

                    b.Property<int?>("HeartRateMax")
                        .HasColumnType("int");

                    b.Property<int?>("HeartRateMin")
                        .HasColumnType("int");

                    b.Property<int?>("HrvAverage")
                        .HasColumnType("int");

                    b.Property<int?>("OptimalBedtimeEnd")
                        .HasColumnType("int");

                    b.Property<int?>("OptimalBedtimeStart")
                        .HasColumnType("int");

                    b.Property<double?>("ProteinGrams")
                        .HasColumnType("float");

                    b.Property<int?>("ReadinessScore")
                        .HasColumnType("int");

                    b.Property<int?>("RemSleepDuration")
                        .HasColumnType("int");

                    b.Property<string>("ResilienceLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SleepEfficiency")
                        .HasColumnType("int");

                    b.Property<int?>("SleepScore")
                        .HasColumnType("int");

                    b.Property<double?>("SpO2Average")
                        .HasColumnType("float");

                    b.Property<int?>("Steps")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSleepDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<double?>("Vo2Max")
                        .HasColumnType("float");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<int?>("WorkoutCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .IsDescending()
                        .HasDatabaseName("UQ_DailySummaries_Date");

                    b.ToTable("DailySummaries", (string)null);
                });

            modelBuilder.Entity("HealthAggregatorV2.Domain.Entities.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MetricTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_Measurements_Timestamp");

                    b.HasIndex("MetricTypeId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Measurements_MetricType_Timestamp");

                    b.HasIndex("SourceId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Measurements_Source_Timestamp");

                    b.HasIndex("MetricTypeId", "SourceId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("UQ_Measurements_Unique");

                    b.ToTable("Measurements", (string)null);
                });

            modelBuilder.Entity("HealthAggregatorV2.Domain.Entities.MetricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double?>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_MetricTypes_Category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_MetricTypes_Name");

                    b.ToTable("MetricTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Overall sleep quality score",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "sleep_score",
                            Unit = "score",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Total time asleep",
                            MaxValue = 86400.0,
                            MinValue = 0.0,
                            Name = "total_sleep_duration",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time in deep sleep stage",
                            MaxValue = 43200.0,
                            MinValue = 0.0,
                            Name = "deep_sleep_duration",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time in REM sleep stage",
                            MaxValue = 43200.0,
                            MinValue = 0.0,
                            Name = "rem_sleep_duration",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time in light sleep stage",
                            MaxValue = 43200.0,
                            MinValue = 0.0,
                            Name = "light_sleep_duration",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time awake during sleep period",
                            MaxValue = 43200.0,
                            MinValue = 0.0,
                            Name = "awake_time",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Percentage of time in bed actually sleeping",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "sleep_efficiency",
                            Unit = "%",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time to fall asleep",
                            MaxValue = 7200.0,
                            MinValue = 0.0,
                            Name = "sleep_latency",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Total time in bed",
                            MaxValue = 86400.0,
                            MinValue = 0.0,
                            Name = "time_in_bed",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Number of restless periods during sleep",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "restless_periods",
                            Unit = "count",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Daily readiness score",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "readiness_score",
                            Unit = "score",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Body temperature deviation from baseline",
                            MaxValue = 5.0,
                            MinValue = -5.0,
                            Name = "temperature_deviation",
                            Unit = "°C",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Overall activity score",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "activity_score",
                            Unit = "score",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Total steps taken",
                            MaxValue = 100000.0,
                            MinValue = 0.0,
                            Name = "steps",
                            Unit = "steps",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Calories burned from activity",
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "active_calories",
                            Unit = "kcal",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Total calories burned including BMR",
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "total_calories",
                            Unit = "kcal",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Equivalent walking distance",
                            MaxValue = 100000.0,
                            MinValue = 0.0,
                            Name = "equivalent_walking_distance",
                            Unit = "meters",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time in high intensity activity",
                            MaxValue = 86400.0,
                            MinValue = 0.0,
                            Name = "high_activity_time",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time in medium intensity activity",
                            MaxValue = 86400.0,
                            MinValue = 0.0,
                            Name = "medium_activity_time",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time in low intensity activity",
                            MaxValue = 86400.0,
                            MinValue = 0.0,
                            Name = "low_activity_time",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Time spent sedentary",
                            MaxValue = 86400.0,
                            MinValue = 0.0,
                            Name = "sedentary_time",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Number of inactivity alerts",
                            MaxValue = 50.0,
                            MinValue = 0.0,
                            Name = "inactivity_alerts",
                            Unit = "count",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Body weight",
                            MaxValue = 300.0,
                            MinValue = 20.0,
                            Name = "weight",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Body Mass Index",
                            MaxValue = 60.0,
                            MinValue = 10.0,
                            Name = "bmi",
                            Unit = "kg/m²",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Body fat percentage",
                            MaxValue = 70.0,
                            MinValue = 3.0,
                            Name = "body_fat",
                            Unit = "%",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Body water percentage",
                            MaxValue = 80.0,
                            MinValue = 30.0,
                            Name = "body_water",
                            Unit = "%",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bone mass",
                            MaxValue = 10.0,
                            MinValue = 1.0,
                            Name = "bone_mass",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Metabolic age estimate",
                            MaxValue = 100.0,
                            MinValue = 10.0,
                            Name = "metabolic_age",
                            Unit = "years",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Visceral fat level",
                            MaxValue = 30.0,
                            MinValue = 1.0,
                            Name = "visceral_fat",
                            Unit = "level",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basal metabolic rate",
                            MaxValue = 5000.0,
                            MinValue = 500.0,
                            Name = "basal_metabolism",
                            Unit = "kcal",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            Category = "Body",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Skeletal muscle mass",
                            MaxValue = 100.0,
                            MinValue = 10.0,
                            Name = "skeletal_muscle_mass",
                            Unit = "kg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Average heart rate",
                            MaxValue = 220.0,
                            MinValue = 30.0,
                            Name = "heart_rate_avg",
                            Unit = "bpm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minimum/resting heart rate",
                            MaxValue = 220.0,
                            MinValue = 30.0,
                            Name = "heart_rate_min",
                            Unit = "bpm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Maximum heart rate",
                            MaxValue = 220.0,
                            MinValue = 30.0,
                            Name = "heart_rate_max",
                            Unit = "bpm",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Average heart rate variability",
                            MaxValue = 300.0,
                            MinValue = 0.0,
                            Name = "hrv_average",
                            Unit = "ms",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Average breathing rate during sleep",
                            MaxValue = 30.0,
                            MinValue = 5.0,
                            Name = "average_breath",
                            Unit = "breaths/min",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 58,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Daily stress level (0=restored, 1=normal, 2=stressful)",
                            MaxValue = 2.0,
                            MinValue = 0.0,
                            Name = "daily_stress",
                            Unit = "level",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 59,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Resilience level (0=limited, 1=adequate, 2=solid, 3=strong, 4=exceptional)",
                            MaxValue = 4.0,
                            MinValue = 0.0,
                            Name = "resilience_level",
                            Unit = "level",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 60,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "VO2 Max cardio fitness estimate",
                            MaxValue = 100.0,
                            MinValue = 10.0,
                            Name = "vo2_max",
                            Unit = "ml/kg/min",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 61,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cardiovascular age estimate",
                            MaxValue = 150.0,
                            MinValue = 10.0,
                            Name = "cardiovascular_age",
                            Unit = "years",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 62,
                            Category = "Heart",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Average SpO2 blood oxygen saturation",
                            MaxValue = 100.0,
                            MinValue = 70.0,
                            Name = "spo2_average",
                            Unit = "%",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 63,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Optimal bedtime start offset from midnight",
                            MaxValue = 43200.0,
                            MinValue = -43200.0,
                            Name = "optimal_bedtime_start",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 64,
                            Category = "Sleep",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Optimal bedtime end offset from midnight",
                            MaxValue = 43200.0,
                            MinValue = -43200.0,
                            Name = "optimal_bedtime_end",
                            Unit = "seconds",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 65,
                            Category = "Activity",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Number of workouts recorded",
                            MaxValue = 20.0,
                            MinValue = 0.0,
                            Name = "workout_count",
                            Unit = "count",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Total calories consumed",
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "calories_consumed",
                            Unit = "kcal",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protein intake",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Name = "protein",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carbohydrate intake",
                            MaxValue = 1000.0,
                            MinValue = 0.0,
                            Name = "carbs",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fat intake",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Name = "fat",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fiber intake",
                            MaxValue = 200.0,
                            MinValue = 0.0,
                            Name = "fiber",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sugar intake",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Name = "sugars",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Net carbs (carbs minus fiber)",
                            MaxValue = 1000.0,
                            MinValue = 0.0,
                            Name = "net_carbs",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sodium intake",
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "sodium",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cholesterol intake",
                            MaxValue = 2000.0,
                            MinValue = 0.0,
                            Name = "cholesterol",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Water intake",
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "water",
                            Unit = "ml",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Caffeine intake",
                            MaxValue = 2000.0,
                            MinValue = 0.0,
                            Name = "caffeine",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Alcohol intake",
                            MaxValue = 500.0,
                            MinValue = 0.0,
                            Name = "alcohol",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vitamin D intake",
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "vitamin_d",
                            Unit = "IU",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vitamin B12 intake",
                            MaxValue = 1000.0,
                            MinValue = 0.0,
                            Name = "vitamin_b12",
                            Unit = "µg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Iron intake",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "iron",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Calcium intake",
                            MaxValue = 5000.0,
                            MinValue = 0.0,
                            Name = "calcium",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Magnesium intake",
                            MaxValue = 2000.0,
                            MinValue = 0.0,
                            Name = "magnesium",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 54,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zinc intake",
                            MaxValue = 100.0,
                            MinValue = 0.0,
                            Name = "zinc",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 55,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Potassium intake",
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "potassium",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 56,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vitamin C intake",
                            MaxValue = 5000.0,
                            MinValue = 0.0,
                            Name = "vitamin_c",
                            Unit = "mg",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 57,
                            Category = "Nutrition",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Omega-3 fatty acids intake",
                            MaxValue = 50.0,
                            MinValue = 0.0,
                            Name = "omega_3",
                            Unit = "g",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthAggregatorV2.Domain.Entities.Source", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKeyEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_Sources_IsEnabled");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sources_ProviderName");

                    b.ToTable("Sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            ProviderName = "Oura",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            ProviderName = "Picooc",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            ProviderName = "Cronometer",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsEnabled = true,
                            ProviderName = "Manual",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthAggregatorV2.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("HealthAggregatorV2.Domain.Entities.MetricType", "MetricType")
                        .WithMany("Measurements")
                        .HasForeignKey("MetricTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthAggregatorV2.Domain.Entities.Source", "Source")
                        .WithMany("Measurements")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetricType");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HealthAggregatorV2.Domain.Entities.MetricType", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("HealthAggregatorV2.Domain.Entities.Source", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
